// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String fileVerify({required List<int> data, required int selected}) => RustLib
    .instance
    .api
    .crateServicesApiFileVerify(data: data, selected: selected);

String convertTextFormat({
  required String input,
  required int inputFormat,
  required int outputFormat,
}) => RustLib.instance.api.crateServicesApiConvertTextFormat(
  input: input,
  inputFormat: inputFormat,
  outputFormat: outputFormat,
);
